name: Spell Check

on:
  pull_request:
    paths:
      - '**/*.md'
    types: [opened, synchronize, reopened]

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install codespell
        run: |
          sudo apt-get update
          sudo apt-get install -y codespell

      - name: Run codespell
        run: |
          codespell --ignore-words-list="hte" --skip="*.json,*.yaml" --check-filenames --check-hidden --quiet-level=3
        continue-on-error: true

      - name: Annotate PR with spell check results
        if: failure()
        run: |
          echo "### Spelling Mistakes Found" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          codespell --ignore-words-list="hte" --skip="*.json,*.yaml" --check-filenames --check-hidden --quiet-level=3 >> $GITHUB_STEP_SUMMARY
